# W55FA93 series audio


snd-soc-w55fa93adc-adc-objs := w55fa93adc-adc.o
snd-soc-w55fa93adc-pcm-objs := w55fa93adc-pcm.o

obj-$(CONFIG_SND_SOC_W55FA93) += snd-soc-w55fa93adc-pcm.o
obj-$(CONFIG_SND_SOC_W55FA93) += snd-soc-w55fa93adc-adc.o

# Boards
snd-soc-w55fa93adc-audio-objs := w55fa93adc-audio.o
obj-$(CONFIG_SND_SOC_W55FA93) += snd-soc-w55fa93adc-audio.o
