#!/bin/sh    
/bin/mount -t proc none /proc
/bin/mount -t sysfs sysfs /sys
/bin/mount -t devtmpfs devtmpfs /dev
/bin/mkdir /dev/pts
/bin/mount -t devpts devpts /dev/pts
/bin/echo > /dev/mdev.seq
/bin/echo /sbin/mdev > /proc/sys/kernel/hotplug
# move mdev scan to /etc/profile to avoid usbdisk affect the NAND booting
#/sbin/mdev -s

