# W55FA93 series audio

#snd-soc-w55fa93-i2s-objs := w55fa93_i2s.o
#snd-soc-w55fa93-spu-objs := w55fa93_spu.o
#snd-soc-w55fa93-audio-objs := w55fa93_audio.o
#snd-soc-w55fa93-nau8822-objs := w55fa93_nau8822.o
#snd-soc-w55fa93-nau8810-objs := w55fa93_nau8810.o
#snd-soc-w55fa93-nau8814-objs := w55fa93_nau8814.o
# W55FA93 series audio

snd-soc-w55fa93-dac-objs := w55fa93_dac.o
snd-soc-w55fa93-spu-objs := w55fa93_spu.o
snd-soc-w55fa93-i2s-objs := w55fa93_i2s.o
snd-soc-w55fa93-pcm-objs := w55fa93_pcm.o
snd-soc-w55fa93-audio-objs := w55fa93_audio.o

obj-$(CONFIG_SND_SOC_W55FA93_SPU) += snd-soc-w55fa93-dac.o snd-soc-w55fa93-pcm.o snd-soc-w55fa93-spu.o snd-soc-w55fa93-audio.o 
obj-$(CONFIG_SND_SOC_W55FA93_I2S) += snd-soc-w55fa93-i2s.o snd-soc-w55fa93-pcm.o snd-soc-w55fa93-audio.o
